version: '2'
services:
  user:
      image: java:8
      container_name: user
      ports:
        - 80:8081
      volumes:
        - ./backend:/home/app
        - ~/.gradle:/root/.gradle
      command: sh -c "cd /home/app && ./gradlew clean build && java -jar build/libs/backend-0.0.1-SNAPSHOT.jar --spring.profiles.active=prod"
      networks:
        main:
          aliases:
            - user
networks:
  main: